services:
  - type: web
    name: cliente-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
